# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - dev

pool:
  name: 'ERP_DEV'

jobs:
  - job: DotNetBuild
    steps:
      - script: |
          export PATH=$PATH:/opt/dotnet6/
          cd src/W2.DbMigrator
          dotnet6 publish -c Release
        displayName: 'Dotnet Release Migrator'

      - script: |
          cd src/W2.DbMigrator/bin/Release/net6.0/publish
          zip -r backend_migrator.zip *
        displayName: 'Compress Build Migrator'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'src/W2.DbMigrator/bin/Release/net6.0/publish/backend_migrator.zip'
          ArtifactName: 'dev-dotnet-migrator-w2'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts Migrator'

      - script: |
          export PATH=$PATH:/opt/dotnet6/
          export DOTNET_ROOT=/opt/dotnet6/
          export PATH="$PATH:/home/nccsoft/.dotnet/tools"
          cd src/W2.Web/
          abp install-libs
          dotnet6 publish -c Release
        displayName: 'Dotnet Build Host'

      - script: |
          cd src/W2.Web/bin/Release/net6.0/publish/
          zip -r backend_publish.zip *
        displayName: 'Compress Build Host'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'src/W2.Web/bin/Release/net6.0/publish/backend_publish.zip'
          ArtifactName: 'dev-dotnet-host-w2'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts Host'