name: Deploy Workflow W2
on:
  push:
    branches:
      - cicd
    tags:
      - '*'

jobs:
  build:
    runs-on:  [self-hosted, w2, ${{ github.ref }} ]
    name: Build Workflow W2
    environment: ${{ github.ref_name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Migrator
      run: |
        export PATH=$PATH:/opt/dotnet6/
        cd src/W2.DbMigrator
        dotnet6 publish -c Release
    
    - name: Publish migrator
      run: |
        rm -rf src/W2.DbMigrator/bin/Release/net6.0/publish/appsettings.json
        cp -r src/W2.DbMigrator/bin/Release/net6.0/publish/* /var/www/migrator/w2/dev-dotnet-migrator-w2/
    
    - name: Build Host
      run: |
        export PATH=$PATH:/opt/dotnet6/
        export DOTNET_ROOT=/opt/dotnet6/
        export PATH="$PATH:/home/nccsoft/.dotnet/tools"
        export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
        nvm use 14.15
        cd src/W2.Web/
        abp install-libs
        dotnet6 publish -c Release
        sudo service erp-w2 stop
    
    - name: Publish Host
      run: |
        rm -rf src/W2.Web/bin/Release/net6.0/publish/appsettings.json
        cp -r src/W2.Web/bin/Release/net6.0/publish/* /var/www/app/w2/dev-dotnet-host-w2/
  deploy:
    runs-on:  [self-hosted, w2, github.ref_name ]
    name: Deploy Workflow W2
    environment: ${{ github.ref_name }}
    needs:
      - build
    steps:
    - name: Migrate Database
      run: |
        export PATH=$PATH:/opt/dotnet6/
        cd /var/www/migrator/w2/dev-dotnet-migrator-w2/
        dotnet6 W2.DbMigrator.dll -q
    
    - name: Restart Server
      run: |
        cd /var/www/app/w2/dev-dotnet-host-w2/
        mkdir -p /var/www/app/w2/dev-dotnet-host-w2/Logs/
        touch /var/www/app/w2/dev-dotnet-host-w2/Logs/logs.txt
        chmod 777 -R Logs/
        chmod 777 -R wwwroot/
        cp appsettings.json appsettings.Development.json
        sudo service erp-w2 start
        sudo service erp-w2 status
