name: Deploy Workflow W2 prod
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on:  [self-hosted, w2, dev]
    name: Build Workflow W2 Production
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Migrator
      run: |
        export PATH=$PATH:/opt/dotnet6/
        cd src/W2.DbMigrator
        dotnet6 publish -c Release
    
    - name: Composer Migrator
      run: |
        cd src/W2.DbMigrator/bin/Release/net6.0/publish/
        rm -rf appsettings.json
        zip -r migrator.zip *
    - name: Publish Migrator
      uses: actions/upload-artifact@v3
      with:
        path: src/W2.DbMigrator/bin/Release/net6.0/publish/migrator.zip
        name: w2-migrator
    
    - name: Build Host
      run: |
        export PATH=$PATH:/opt/dotnet6/
        export DOTNET_ROOT=/opt/dotnet6/
        export PATH="$PATH:/home/nccsoft/.dotnet/tools"
        export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh"
        nvm use 14.15
        cd src/W2.Web/
        abp install-libs
        dotnet6 publish -c Release
    
    - name: Composer Host
      run: |
        cd src/W2.Web/bin/Release/net6.0/publish/
        rm -rf appsettings.json
        zip -r host.zip *
        
    - name: Publish Host
      uses: actions/upload-artifact@v3
      with:
        path: src/W2.Web/bin/Release/net6.0/publish/host.zip
        name: w2-host
        
  deploy:
    runs-on:  [self-hosted, w2, prod]
    name: Deploy Workflow W2 Production
    environment: production
    needs:
      - build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Update Appsettings and Backup Database
      run: |
        bash parse_env.sh
        cd /home/erp/.backup_db/ && bash backup_w2.sh
      env:
        API_URL: ${{ secrets.API_URL_PROD }}
        DB_HOST: ${{ secrets.DB_HOST_prod }}
        DB_NAME: ${{ secrets.DB_NAME_prod }}
        DB_PASS: ${{ secrets.DB_PASS_prod }}
        DB_USER: ${{ secrets.DB_USER_prod }}
        DB_PORT: ${{ secrets.DB_PORT_prod }}
        PASSPHRASE: ${{ secrets.PASSPHRASE_prod }}
        SES_HOST: ${{ secrets.SES_HOST_prod }}
        SES_USER: ${{ secrets.SES_USER_prod }}
        SES_PASS: ${{ secrets.SES_PASS_prod }}
        GG_CLIENT: ${{ secrets.GG_CLIENT_prod }}
        GG_SECRET: ${{ secrets.GG_SECRET_prod }}
        TALENT_DF: ${{ secrets.TALENT_DF_prod }}
        
    - name: Download Artifact Migrator
      uses: actions/download-artifact@v3
      with:
        name: w2-migrator
        path: /var/www/migrator/w2/prod-dotnet-migrator-w2/
    
    - name: Download Artifact Host
      uses: actions/download-artifact@v3
      with:
        name: w2-host
        path: /var/www/app/w2/prod-dotnet-host-w2/
    
    - name: Migrate Database
      run: |
        export PATH=$PATH:/opt/dotnet6/
        cp appsettings.json /var/www/migrator/w2/prod-dotnet-migrator-w2/
        cd /var/www/migrator/w2/prod-dotnet-migrator-w2/
        unzip -qo migrator.zip && rm -rf migrator.zip
        dotnet6 W2.DbMigrator.dll -q
    
    - name: Restart Server
      run: |
        sudo service erp-w2 stop
        cp appsettings.json /var/www/app/w2/prod-dotnet-host-w2/
        cd /var/www/app/w2/prod-dotnet-host-w2/
        unzip -qo host.zip && rm -rf host.zip
        mkdir -p /var/www/app/w2/prod-dotnet-host-w2/Logs/
        touch /var/www/app/w2/prod-dotnet-host-w2/Logs/logs.txt
        chmod 777 -R Logs/
        chmod 777 -R wwwroot/
        cp appsettings.json appsettings.Production.json
        sudo service erp-w2 start
        sudo service erp-w2 status
